[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
num-format = "0.4.4"
lazy_static = "1.5.0"
serde = { version = "1", features = ["derive"] }
esosim-data = { git = "https://github.com/sheumais/esosim/" }
esosim-models = { git = "https://github.com/sheumais/esosim/" } 